name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:EnableWindowsTargeting=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create ZIP file
      run: zip -r "${{ github.repository }}.zip" . # Crea un archivo ZIP con el nombre del repositorio
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Utiliza el GITHUB_TOKEN automáticamente proporcionado
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ github.repository }}.zip # Ruta del archivo ZIP creado
        asset_name: ${{ github.repository }}.zip # Nombre del archivo ZIP
        asset_content_type: application/zip
