name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /p:EnableWindowsTargeting=true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create ZIP file
      run: |
        mkdir -p output/${{ github.repository }}
        zip -r "output/${{ github.repository }}.zip" .
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./output/${{ github.repository }}.zip
        asset_name: ${{ github.repository }}.zip
        asset_content_type: application/zip
